- app/layout.tsx
- package.json
- pnpm-lock.yaml
- styles/index.ts
- Added Urbanist font
- Added mantine UI provider in layout
https://app.clickup.com/t/86erxgjmg
> CU-86erxgjmg-WEB-Add-Font: Add Urbanist font, add mantine UI

- app/verification/page.tsx
- app/verification/schema/verifyOtp.ts
- app/verification/viewModules/OtpTimer.tsx
- app/verification/viewModules/VerifyOtpForm.tsx
- package.json
- add otp verification page
https://app.clickup.com/t/86ery73rh
> CU-86ery73rh-email-verfication-system: Add Otp verification page

- app/layout.tsx
- app/organization/layout.tsx
- app/organization/page.tsx
- app/organization/schema/organization.ts
- app/organization/viewModules/CreateOrganizationForm.tsx
- components/DsmCustomIcon/CustomIcons/OranizationIcon.tsx
- components/DsmCustomIcon/CustomIcons/index.ts
- components/DsmTextAreaInput/index.tsx
- components/DsmTextAreaInput/types.ts
- package.json
- add create organization page
- added DsmTextarea component
https://app.clickup.com/t/86ery73zy
> CU-86ery73zy-create-organization: Add create organization page

- app/login/actions.ts
- app/verification/actions.ts
- add domain in cookies for access of same cookie in the dsm app
https://app.clickup.com/t/86ery746b
> CU-86ery746b-Website-Intergration: add domain in cookie for access in app

- app/login/actions.ts
- app/verification/actions.ts
- renamed cookie domain from ".app.dailysync.ai" to ".dailysync.ai"
https://app.clickup.com/t/86et5fab5
> CU-86et5fab5-BUG-rename-cookie-domain: rename domain in cookies

- app/(private-layout)/(stepper-layout)/invite-employee/_viewModules/InviteEmployeeFormView/InviteEmployeeForm.tsx
- app/(private-layout)/(stepper-layout)/invite-employee/_viewModules/InviteEmployeeFormView/index.tsx
- app/(private-layout)/get-started/_viewModules/OrganizationListView.tsx
- app/(private-layout)/get-started/_viewModules/OrganizationNavBtn.tsx
- app/(private-layout)/get-started/actions.ts
- app/layout.tsx
- app/login/actions.ts
- app/verification/actions.ts
- constants/commons.ts
- moved dsm app url to constants and env file
- set new cookie that holds organization id when navigating to an organization from website
https://app.clickup.com/t/86et6064j
> CU-86et6064j-Add-organization-navigation-in-website-with-cookie: add cookie for organization navigation

- .env.example
- .gitignore
- app/(private-layout)/(stepper-layout)/layout.tsx
- app/(private-layout)/get-started/_viewModules/OrganizationNavBtn.tsx
- open organization in same tab
- added overflow in stepper layout
https://app.clickup.com/t/86et8eqnr
> CU-86et8eqnr-open-organization-in-same-tab | DSM Website open organization in same tab

- .env.example
- .gitignore
- app/(private-layout)/(stepper-layout)/layout.tsx
- app/(private-layout)/get-started/_viewModules/OrganizationNavBtn.tsx
CU-86et8eqnr-open-organization-in-same-tab | DSM Website open organization in same tab #20
> uat <- develop

- app/(private-layout)/(stepper-layout)/invite-employee/_viewModules/InviteEmployeeFormView/InviteEmployeeForm.tsx
- app/(private-layout)/(stepper-layout)/invite-employee/_viewModules/InviteEmployeeFormView/index.tsx
- app/(private-layout)/get-started/actions.ts
- app/(private-layout)/get-started/page.tsx
- lib/api/endpoints/organization.ts
- changed the organization list api
- fixed dsm-app nav in invite employee
https://app.clickup.com/t/86eta0dxe
> fix(CU-86eta0dxe-org-list): changed the organization list API

- app/(private-layout)/invitation/page.tsx
- app/(private-layout)/invitation/types.ts
- invitation key added to accept invitation API
https://app.clickup.com/t/86etm70ct
> CU-86etm70ct-REFACTOR-Add-invitation-key-in-accept-invitation-API | Add invitation key in accept invitation API

- app/(private-layout)/(stepper-layout)/invite-employee/_viewModules/InviteEmployeeFormView/InviteEmployeeForm.tsx
- app/(private-layout)/(stepper-layout)/organization/_viewModules/CreateOrganizationFormView/CreateOrganizationForm.tsx
- app/(private-layout)/get-started/_viewModules/OrganizationListView.tsx
Add primary color on onboarding flow
> fix(CU-86etqhhrm-UI-fix-color-for-onboarding) | Add primary color on onboarding flow

- .github/PULL_REQUEST_TEMPLATE.md
> feat(CU-86etqhnmw): add PR template in github

- app/(private-layout)/get-started/_viewModules/OrganizationNavBtn.tsx
- constants/dataTestId.ts
https://app.clickup.com/t/86etrrvuv
add dynamic data test id for organization nav btn
> fix(CU-86etrrvuv) | Add dynamic data test id for organization nav btn

- app/_home/_viewModules/StandupStepsView/index.tsx
- app/forgot-password/_viewModules/ForgotPasswordFormView/index.module.css
- app/login/_viewModules/LoginFormView/index.module.css
- app/sign-up/_viewModules/SignUpFormView/index.module.css
https://app.clickup.com/t/86etthf19
build time error in css file fixed
> fix(CU-86etthf19-HOT-FIX) |  Build time error fix

- Dockerfile
- docker-compose-dev.yml
https://app.clickup.com/t/86ett8u7h
> CU-86ett8u7h - [DevOps]Perform Containerization of dsm-mono,dsm-website and dsm-ai

- app/_home/_constants/index.ts
- app/_home/_viewModules/AccordionView/index.tsx
https://app.clickup.com/t/86ettz4ww
update FAQ content in homepage 
> fix(CU-86ettz4ww-fix-update-FAQ-content) | Update FAQ content

- .github/workflows/actions_website_dev.yml
- docker-compose-dev.yml
https://app.clickup.com/t/86ettz7wf
> CU-86ettz7wf - [CICD]Create Github Actions CICD script for dsm-website

- app/(private-layout)/invitation/page.tsx
- components/DsmNavigateBackBtn/index.tsx
https://app.clickup.com/t/86ett9e5w
Change invitation email for the user in different organization
> featCU-86ett9e5w) | Change invitation email for the user in different organization

- .github/workflows/actions_website_prod.yml
- docker-compose-prod.yml
> CU-86etvpmpt - [DevOps]Create docker-compose dockerfile and make dsm production ready

- app/(private-layout)/get-started/index.module.css
- app/(private-layout)/get-started/page.tsx
- app/login/_viewModules/LoginFormView/LoginForm.tsx
https://app.clickup.com/t/86etw496m
Comment remember me checkbox in login form
> fix(CU-86etw496m) | Comment remember me checkbox in login form

- docker-compose-prod.yml
> uat => main

- .github/workflows/actions_website_prod.yml
- docker-compose-prod.yml
https://app.clickup.com/t/86etwed65
> CU-86etwed65 - [BUG]Fix script of website

- app/(private-layout)/get-started/page.tsx
- Same Organization card in organization list
- remove duplicate orgs from the org list page
> fCU-86ety4ekk | [BUG] Same Organization card in organization list

- app/verification/_viewModules/VerifyOtpFormView/OtpTimer.tsx
- app/verification/_viewModules/VerifyOtpFormView/VerifyOtpForm.tsx
- app/verification/page.tsx
- app/verification/types.ts
https://app.clickup.com/t/86eu0y5pa
- reset the otp form when clicking `click to resend`
> refactor(CU-86eu0y5pa-reset-otp): reset the otp form when clicking click-to-resend

- app/(private-layout)/(stepper-layout)/invite-employee/_viewModules/InviteEmployeeFormView/InviteEmployeeForm.tsx
- app/(private-layout)/_viewModules/AppBarView.tsx
- app/(private-layout)/get-started/_viewModules/OrganizationListView.tsx
- app/(private-layout)/get-started/page.tsx
- app/forgot-password/_viewModules/ForgotPasswordFormView/ForgotPasswordForm.tsx
- app/login/_viewModules/LoginFormView/index.tsx
- app/reset-password/_viewModules/ResetPasswordFormView/ResetPasswordFrom.tsx
- app/sign-up/_viewModules/SignUpFormView/index.tsx
- app/verification/_viewModules/VerifyOtpFormView/index.tsx
- constants/commons.ts
- constants/routeConstants.ts
https://app.clickup.com/t/86eu36qk9
- update the footer in organization list page
- renamed the form submit buttons with more sensible names
- fixed the new signup user redirect to create organization page
- show toast message for error  code in resposne 
> refactor(CU-86eu36qk9-update-organization-list-footer): update the organization list page footer

- app/(private-layout)/(stepper-layout)/invite-employee/_viewModules/InviteEmployeeFormView/InviteEmployeeForm.tsx
- app/(private-layout)/(stepper-layout)/layout.tsx
- app/(private-layout)/(stepper-layout)/organization/_viewModules/CreateOrganizationFormView/CreateOrganizationForm.tsx
- app/(private-layout)/(stepper-layout)/organization/page.tsx
- app/(private-layout)/get-started/_components/OrganizationCard/index.module.css
- app/(private-layout)/get-started/_components/OrganizationCard/index.tsx
- app/(private-layout)/get-started/page.tsx
- biome.json
- components/DsmFormWrapper/index.tsx
- components/DsmProfileImgUploader/index.tsx
- components/DsmTextAreaInput/index.tsx
- package.json
- pnpm-lock.yaml
- reafactor the UI with color changes and spacing adjustment
- add biome to the project as linter and formatter
> refactor(refactor-ui): refactor the UI colors and spacing

- .husky/pre-commit
- package.json
- pnpm-lock.yaml
- add husky for pre-commit linting
> feat(add-husky): add husky for pre-commit linting

- app/(private-layout)/get-started/_viewModules/OrganizationListView.tsx
- app/(private-layout)/get-started/page.tsx
- components/DsmContentWrapper/index.tsx
https://app.clickup.com/t/86eu4n078
- rework the get started page for users that have organization
> refactor(CU-86eu4n078-orgnaization-list-page-rework): rework the organization list page

- app/_home/_constants/index.ts
- app/_home/_viewModules/PricingView/index.tsx
- app/_home/_viewModules/StandupStepsView/index.tsx
- app/_home/page.tsx
- refactor the pricing list
- refactor testimonials
- fix mobile view text size and spacing in homepage
> refactor-pricing: refactor the pricing list
